export enum EXCEPTION_CODES {
  HTTP_EXCEPTION = "HTTP_EXCEPTION",
  UNAUTHORIZED = "UNAUTHORIZED",
  NOT_FOUND = "NOT_FOUND",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  VALIDATION = "VALIDATION_ERROR",
}
